### ISSUE TITLE
Trying to understand Trino Except regarding HIVE_FILESYSTEM_ERROR

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/os_c_data_commons#117]
I've created a prototype Data Vault in ITR (https://github.com/os-climate/ITR/blob/develop-project-vault/test/test_vault_providers.py).  When I initialize `engine_init` with my own credentials and use the schema `itr_mdt` it functions as expected.  When I try to use a different schema, such as `demo` I get this:

```
======================================================================
ERROR: test_N0_projections (test_vault_providers.TestVaultProvider)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/app-root/src/ITR/test/test_vault_providers.py", line 60, in setUp
    self.vault_production_bm = VaultProviderProductionBenchmark(engine_init, ingest_schema, benchmark_name="benchmark_prod", production_benchmarks=prod_bms)
  File "/opt/app-root/src/ITR/ITR/data/vault_providers.py", line 206, in __init__
    df.to_sql(benchmark_name, self._engine, index=False, chunksize=200, method='multi')
  File "/opt/app-root/lib64/python3.8/site-packages/pandas/core/generic.py", line 2928, in to_sql
    return sql.to_sql(
  File "/opt/app-root/lib64/python3.8/site-packages/pandas/io/sql.py", line 697, in to_sql
    return pandas_sql.to_sql(
  File "/opt/app-root/lib64/python3.8/site-packages/pandas/io/sql.py", line 1723, in to_sql
    table = self.prep_table(
  File "/opt/app-root/lib64/python3.8/site-packages/pandas/io/sql.py", line 1622, in prep_table
    table.create()
  File "/opt/app-root/lib64/python3.8/site-packages/pandas/io/sql.py", line 835, in create
    self._execute_create()
  File "/opt/app-root/lib64/python3.8/site-packages/pandas/io/sql.py", line 821, in _execute_create
    self.table.create(bind=self.pd_sql.connectable)
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/sql/schema.py", line 943, in create
    bind._run_ddl_visitor(ddl.SchemaGenerator, self, checkfirst=checkfirst)
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 3008, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 2016, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 483, in traverse_single
    return meth(obj, **kw)
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 890, in visit_table
    self.connection.execute(
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1200, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 77, in _execute_on_connection
    return connection._execute_ddl(
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1290, in _execute_ddl
    ret = self._execute_context(
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1748, in _execute_context
    self._handle_dbapi_exception(
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1933, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_context
    self.dialect.do_execute(
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy_trino/dialect.py", line 275, in do_execute
    cursor.description  # noqa
  File "/opt/app-root/lib64/python3.8/site-packages/trino/dbapi.py", line 202, in description
    if self._query.columns is None:
  File "/opt/app-root/lib64/python3.8/site-packages/trino/client.py", line 480, in columns
    self._result._rows += self.fetch()
  File "/opt/app-root/lib64/python3.8/site-packages/trino/client.py", line 520, in fetch
    status = self._request.process(response)
  File "/opt/app-root/lib64/python3.8/site-packages/trino/client.py", line 390, in process
    raise self._process_error(response["error"], response.get("id"))
  File "/opt/app-root/lib64/python3.8/site-packages/trino/client.py", line 365, in _process_error
    raise exceptions.TrinoExternalError(error, query_id)
trino.exceptions.TrinoExternalError: TrinoExternalError(type=EXTERNAL, name=HIVE_FILESYSTEM_ERROR, message="Failed checking path: s3a://redhat-osc-physical-landing-647521352890/data/demo.db/benchmark_prod", query_id=20220115_230034_45621_abma7)

----------------------------------------------------------------------
```

I get the same error message whether I use my own identity or that of `os-climate-user1`.  I cannot write to the schema `itr_mdt` as `os-climate-user1`.  Can you help me understand the nature of the error?  Thanks!

**Comment by MichaelTiemannOSC** [comment]
Related: I cannot simply copy a table in Trino from one schema (where a user does not have permission to select) to another (where that user does):

`engine.execute("create table demo.rmi_company_data as select * from itr_mdt.rmi_company_data").fetchall()`

Throws the same error.  So basically all our Trino writes have to be done partly by hand (which may be a design feature of the data pipeline system).

**Comment by MichaelTiemannOSC** [comment]
I worked around this problem thusly:

```
for t in ['rmi_company_data', 'rmi_emission_data', 'rmi_intensity_data', 'rmi_production_data', 'rmi_trajectory_data']:
    df = pd.read_sql(t, engine)
    df = df.convert_dtypes()
    if 'isic' in df.columns:
        df.isic = df.isic.astype('Int16')
    if 's3_co2' in df.columns:
        df.s3_co2 = df.s3_co2.astype('string')
    if 's3_ei' in df.columns:
        df.s3_ei = df.s3_ei.astype('string')
    print(t)
    try:
        osc.ingest_unmanaged_parquet(df, 'demo', t, trino_bucket)
        qres = engine.execute(osc.unmanaged_parquet_tabledef(df, ingest_catalog, 'demo', t, trino_bucket, typemap={'Int16':'smallint'}))
        print(qres.fetchall())
    except ValueError as e:
        print(df.dtypes)
```

But I also I also needed to use WITH statements when creating tables from scratch in the demo context:

```
        qres = self._engine.execute(f"""
create table cumulative_emissions with (
    format = 'parquet',
    external_location = 's3a://{trino_bucket.name}/trino/{ingest_schema}/cumulative_emissions/'
) as
select C.company_name, C.company_id, '{company_data._company_schema}' as source, 'S1+S2' as scope,
       sum(ET.co2_intensity_trajectory_by_year * P.production_by_year) as cumulative_trajectory,
       sum(EI.co2_intensity_target_by_year * P.production_by_year) as cumulative_target
from {company_data._company_schema}.{company_data._company_table} C
     join {company_data._company_schema}.{company_data._production_table} P on P.company_name=C.company_name
     join {company_data._company_schema}.{company_data._intensity_table} EI on EI.company_name=C.company_name and EI.year=P.year
     join {company_data._company_schema}.{company_data._trajectory_table} ET on ET.company_name=C.company_name and ET.year=P.year
group by C.company_name, C.company_id, '{company_data._company_schema}', 'S1+S2'
""")
        # Need to fetch so table created above is established before using in query below
        qres.fetchall()
```

With that, I've unblocked myself.
