### ISSUE TITLE
Database location error when creating tables on new Trino schemas

### ISSUE THREAD

**Issue by caldeirav** [os-climate/os_c_data_commons#207]

**Comment by caldeirav** [comment]
When creating a table on a new trino schema, we get a HIVE_DATABASE_LOCATION error. There is no error when creating a table in the existing sandbox schema:

SQL:
create table if not exists osc_datacommons_dev.wri_gppd.gppd_source(
    country varchar,
    country_long varchar,
    name varchar,
    gppd_idnr varchar,
    capacity_mw double,
    latitude double,
    longitude double,
    primary_fuel varchar,
    other_fuel1 varchar,
    other_fuel2 varchar,
    other_fuel3 varchar,
    commissioning_year double,
    owner varchar,
    source varchar,
    url varchar,
    geolocation_source varchar,
    wepp_id varchar,
    year_of_capacity_data bigint,
    generation_gwh_2013 double,
    generation_gwh_2014 double,
    generation_gwh_2015 double,
    generation_gwh_2016 double,
    generation_gwh_2017 double,
    generation_gwh_2018 double,
    generation_gwh_2019 double,
    generation_data_source varchar,
    estimated_generation_gwh_2013 double,
    estimated_generation_gwh_2014 double,
    estimated_generation_gwh_2015 double,
    estimated_generation_gwh_2016 double,
    estimated_generation_gwh_2017 double,
    estimated_generation_note_2013 varchar,
    estimated_generation_note_2014 varchar,
    estimated_generation_note_2015 varchar,
    estimated_generation_note_2016 varchar,
    estimated_generation_note_2017 varchar
) with (
    format = 'ORC',
    partitioning = array['country']
)

Exception in Trino:

io.trino.spi.TrinoException: Database 'wri_gppd' location does not exist: file:/opt/hive/warehouse/wri_gppd.db
    at io.trino.plugin.hive.util.HiveWriteUtils.getTableDefaultLocation(HiveWriteUtils.java:459)
    at io.trino.plugin.iceberg.catalog.hms.TrinoHiveCatalog.defaultTableLocation(TrinoHiveCatalog.java:313)
    at io.trino.plugin.iceberg.IcebergUtil.lambda$newCreateTableTransaction$8(IcebergUtil.java:583)
    at java.base/java.util.Optional.orElseGet(Optional.java:369)
    at io.trino.plugin.iceberg.IcebergUtil.newCreateTableTransaction(IcebergUtil.java:583)
    at io.trino.plugin.iceberg.IcebergMetadata.beginCreateTable(IcebergMetadata.java:635)
    at io.trino.plugin.iceberg.IcebergMetadata.createTable(IcebergMetadata.java:614)
    at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.createTable(ClassLoaderSafeConnectorMetadata.java:382)
    at io.trino.metadata.MetadataManager.createTable(MetadataManager.java:640)
    at io.trino.execution.CreateTableTask.internalExecute(CreateTableTask.java:270)
    at io.trino.execution.CreateTableTask.execute(CreateTableTask.java:119)
    at io.trino.execution.CreateTableTask.execute(CreateTableTask.java:85)
    at io.trino.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:145)
    at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:243)
    at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
    at io.trino.$gen.Trino_388____20221001_001206_2.run(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by MichaelTiemannOSC** [comment]
I solved a similar problem by manually configuring the location of the essd schema when I created the essd schema.  The default location puts schemas in the wrong location for our environment.

**Comment by caldeirav** [comment]
Solved by specifying a specific location for the schema as:

create schema if not exists osc_datacommons_dev.wri_gppd with (
    location ='s3a://osc-datacommons-s3-bucket-dev02/data/wri_gppd.db/'
)
