### ISSUE TITLE
Add Kafka topic co2signal to Trino Catalog

### ISSUE THREAD

**Issue by bryonbaker** [os-climate/os_c_data_commons#213]
Similar to issue https://github.com/os-climate/os_c_data_commons/issues/193 - can we please add a new Kafka Topic (co2signal) to the Trino catalog.

We are rushing this for Vincent's demo so the code is not yet in OS Climate.

The schema is in this gist: https://gist.github.com/bryonbaker/380b4ca3789e2884e1a588a8fe1bd4ca

You can test there is data in the topic with this command:

`oc run kafka-consumer2 -ti --image=quay.io/strimzi/kafka:latest-kafka-3.0.0 --rm=true --restart=Never -- bin/kafka-console-consumer.sh --bootstrap-server os-climate-kafka-bootstrap.kafka.svc.cluster.local:9092 --topic co2signal --from-beginning`

**Comment by HumairAK** [comment]
When adding this schema this error is encountered

```
io.trino.spi.TrinoException: Cannot list splits for table 'co2signal' reading topic 'tpch.electricitymapco2signal'
	at io.trino.plugin.kafka.KafkaSplitManager.getSplits(KafkaSplitManager.java:110)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorSplitManager.getSplits(ClassLoaderSafeConnectorSplitManager.java:51)
	at io.trino.split.SplitManager.getSplits(SplitManager.java:58)
	at io.trino.sql.planner.SplitSourceFactory$Visitor.visitScanAndFilter(SplitSourceFactory.java:180)
	at io.trino.sql.planner.SplitSourceFactory$Visitor.visitTableScan(SplitSourceFactory.java:154)
	at io.trino.sql.planner.SplitSourceFactory$Visitor.visitTableScan(SplitSourceFactory.java:128)
	at io.trino.sql.planner.plan.TableScanNode.accept(TableScanNode.java:222)
	at io.trino.sql.planner.SplitSourceFactory$Visitor.visitOutput(SplitSourceFactory.java:343)
	at io.trino.sql.planner.SplitSourceFactory$Visitor.visitOutput(SplitSourceFactory.java:128)
	at io.trino.sql.planner.plan.OutputNode.accept(OutputNode.java:83)
	at io.trino.sql.planner.SplitSourceFactory.createSplitSources(SplitSourceFactory.java:108)
	at io.trino.execution.scheduler.PipelinedQueryScheduler$DistributedStagesScheduler.createStageScheduler(PipelinedQueryScheduler.java:1020)
	at io.trino.execution.scheduler.PipelinedQueryScheduler$DistributedStagesScheduler.create(PipelinedQueryScheduler.java:904)
	at io.trino.execution.scheduler.PipelinedQueryScheduler.createDistributedStagesScheduler(PipelinedQueryScheduler.java:310)
	at io.trino.execution.scheduler.PipelinedQueryScheduler.start(PipelinedQueryScheduler.java:291)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:417)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:249)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_398____20221013_202226_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "partitionInfos" is null
	at io.trino.plugin.kafka.KafkaSplitManager.getSplits(KafkaSplitManager.java:72)
	... 21 more

```

**Comment by HumairAK** [comment]
Guessing because topic name here: https://gist.github.com/bryonbaker/380b4ca3789e2884e1a588a8fe1bd4ca#file-co2signal-trino-schema-json-L4 is incorrect. Attempting `co2signal` as the topic in schema.

**Comment by HumairAK** [comment]
The topic name seems incorrect: https://gist.github.com/bryonbaker/380b4ca3789e2884e1a588a8fe1bd4ca#file-co2signal-trino-schema-json-L4

shouldn't it be? co2signal

**Comment by HumairAK** [comment]
my mistake -- didn't realize there was a new kafka instance where this topic is added, I added another kafka catalog for this, seems to work: 

```
~ $ trino --catalog kafka_osclimate --schema electricitymap  --server https://trino-route-odh-trino.apps.odh-cl2.apps.os-climate.org  --user=admin --password 
Password: 
trino:electricitymap> select * from co2signal;
 country_code | country_name | zone_name | status |        datetime         | carbon_intensity | fossel_fuel_percentage |    unit_name    | unit_value | _partition_id | _partition_offset | _message_corrupt |                            >
--------------+--------------+-----------+--------+-------------------------+------------------+------------------------+-----------------+------------+---------------+-------------------+------------------+---------------------------->
 NULL         |              |           | ok     | 2022-10-13 13:00:00.000 |            103.0 |                   19.3 | carbonIntensity | gCO2eq/kWh |             3 |                 0 | false            | {"key":"AUS-SA","country_co>
 NULL         |              |           | ok     | 2022-10-13 13:00:00.000 |            727.0 |                  90.71 | carbonIntensity | gCO2eq/kWh |             2 |                 0 | false            | {"key":"AUS-QLD","country_c>
(2 rows)

Query 20221013_210411_00006_dgirt, FINISHED, 3 nodes
Splits: 10 total, 10 done (100.00%)
0.29 [2 rows, 484B] [6 rows/s, 1.65KB/s]

trino:electricitymap> 

```
